[package]
name = "game_engine"
version = "0.1.0"
authors = ["Mathias Danielsen <Mathais234@hotmail.com>"]

[dependencies]
glium = {version="*"}
obj-rs = { version = "0.4", features = ["glium-support"] }